version: '3.4'

networks: 
  dockersql-network:
    driver: bridge

services:
  testeinvillia:
    image: ${DOCKER_REGISTRY-}testeinvillia
    build:
      context: .
      dockerfile: TesteInvillia/Dockerfile
    container_name: web-invillia
    networks:
      - dockersql-network
    depends_on:
      - sql.database

  sql.database:
    container_name: sqlserver-invillia
    image: mcr.microsoft.com/mssql/server:2017-latest
    networks:
      - dockersql-network