version: '3.4'

services:
  testeinvillia:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44318
    ports:
      - "49640:80"
      - "44318:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  sql.database:
    environment:
      SA_PASSWORD: "PasswordInvillia001"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"